Repository pontem-network/dove, pull requests merged in 2021-08, with the labels that each got.

#102 Dove.man to Doveindex.toml + Clippy
  dove/src/cmd/build.rs
  dove/src/cmd/mod.rs
  dove/src/context.rs
  dove/src/docs/mod.rs
  dove/src/index/mod.rs
  dove/src/index/resolver/chain/loader.rs
  dove/src/index/resolver/git.rs
  dove/src/manifest.rs
  dove/src/tests_helper.rs
  dove/src/transaction.rs
  dove/tests/test_cmd_dove_init.rs
  dove/tests/test_cmd_dove_metadata.rs
  dove/tests/test_cmd_dove_new.rs
  executor/src/executor.rs
  executor/src/explain.rs
  executor/src/format.rs
  executor/src/meta.rs
  lang/decompiler/src/code/exp/pack.rs
  lang/decompiler/src/code/iter.rs
  lang/decompiler/src/functions.rs
  lang/decompiler/src/generics.rs
  lang/decompiler/src/imports.rs
  lang/decompiler/src/script.rs
  lang/decompiler/src/unit.rs
  lang/src/compiler/address/bech32.rs
  lang/src/compiler/address/ss58.rs
  lang/src/compiler/dialects/diem/mod.rs
  lang/src/compiler/mod.rs
  lang/src/compiler/parser.rs
  lang/src/lexer.rs
  language_server/src/main_loop.rs
  language_server/tests/test_compilation_check.rs
  resource-viewer/src/main.rs
  resource-viewer/src/tte.rs
Labels: compiler, decompiler, resource viewer

#91 Dove: bug fix: Windows: Error when cloning a git repository
  dove/src/index/resolver/git.rs
  dove/src/manifest.rs
  dove/tests/test_cmd_dove_run.rs
Labels: bug

#103 bump vcpkg version
  .github/workflows/ci.yaml
Labels: ci

#100 Dove run: Hints: Running a multiscript without specifying the script name
  dove/src/transaction.rs
Labels: bug

#107 CI: bump vcpkg version for release workflow
  .github/workflows/release-tools.yml
Labels: ci

#109 Fix for error mapping
  lang/src/compiler/mod.rs
  lang/src/compiler/preprocessor.rs
Labels: bug, compiler, dove

#110 Dove: removing unused external dependencies
  dove/src/context.rs
  dove/src/index/mod.rs
  dove/src/index/resolver/git.rs
  dove/src/tests_helper.rs
  dove/tests/test_cmd_dove_run.rs
  dove/tests/test_dependency.rs
Labels: bug

#76 Dove test rebase
  .github/workflows/release-new.yml
  Cargo.lock
  dove/Cargo.toml
  dove/src/cli.rs
  dove/src/cmd/build.rs
  dove/src/cmd/docgen.rs
  dove/src/cmd/metadata.rs
  dove/src/cmd/mod.rs
  dove/src/cmd/run.rs
  dove/src/cmd/tx.rs
  dove/src/docs/mod.rs
  dove/src/docs/options.rs
  dove/src/index/meta.rs
  dove/src/index/mod.rs
  dove/src/index/resolver/git.rs
  dove/src/index/store.rs
  dove/src/lib.rs
  dove/src/manifest.rs
  dove/src/transaction/mod.rs
  dove/src/transaction/typevalue.rs
  dove/tests/test_cmd_dove_metadata.rs
  dove/tests/test_cmd_dove_run.rs
  dove/tests/test_cmd_dove_tx.rs
  executor/Cargo.toml
  executor/src/execution.rs
  executor/src/executor.rs
  executor/src/lib.rs
  executor/src/metadata/mod.rs
  executor/src/session.rs
  executor/tests/metadata.rs
  lang/Cargo.toml
  lang/decompiler/src/lib.rs
  lang/dsl/Cargo.toml
  lang/dsl/src/compiler/mod.rs
  lang/dsl/src/lib.rs
  lang/dsl/src/parser/func.rs
  lang/dsl/src/parser/store.rs
  lang/dsl/src/parser/types/mod.rs
  lang/dsl/src/parser/types/pretyptag.rs
  lang/dsl/src/parser/types/to_typeparams.rs
  lang/dsl/tests/ast.rs
  lang/dsl/tests/common.rs
  lang/src/compiler/mod.rs
  lang/src/compiler/parser.rs
  lang/src/flow/builder.rs
  lang/src/flow/checker.rs
  lang/src/flow/meta_extractor.rs
Labels: compiler, ci, decompiler

#134 Bumped vcpkg
  .github/workflows/ci.yaml
Labels: ci

#135 Update readme
  README.md
  resource-viewer/README.md
Labels: documentation, resource viewer

#130 [Prover] Fixed the logic of getting paths.
  dove/src/cmd/prover.rs
Labels: bug

#132 "cargo install --path dove" broke recently
  Cargo.lock
  check_project.sh
  net/Cargo.toml
  net/src/pont/client.rs
  net/src/pont/mod.rs
Labels: bug

#126 Added module functions support
  Cargo.lock
  dove/Cargo.toml
  dove/src/cmd/build.rs
  dove/src/cmd/clean.rs
  dove/src/cmd/docgen.rs
  dove/src/cmd/fetch.rs
  dove/src/cmd/mod.rs
  dove/src/cmd/prover.rs
  dove/src/cmd/run.rs
  dove/src/cmd/test.rs
  dove/src/cmd/tx.rs
  dove/src/context.rs
  dove/src/executor.rs
  dove/src/index/interface.rs
  dove/src/lib.rs
  dove/src/manifest.rs
  dove/src/transaction.rs
  dove/src/tx/builder.rs
  dove/src/tx/cmd.rs
  dove/src/tx/fn_call.rs
  dove/src/tx/mod.rs
  dove/src/tx/model.rs
  dove/src/tx/parser.rs
  dove/src/tx/resolver.rs
  dove/tests/test_cmd_dove_run.rs
  dove/tests/test_cmd_dove_tx.rs
  lang/Cargo.toml
  lang/decompiler/src/lib.rs
  lang/src/compiler/metadata.rs
  lang/src/compiler/mod.rs
  lang/src/compiler/parser.rs
  lang/src/compiler/preprocessor.rs
  language_server/src/inner/analysis.rs
  language_server/src/inner/config.rs
Labels: compiler, decompiler

#137 Update stdlib version.
  Cargo.lock
  dove/Cargo.toml
  dove/src/lib.rs
Labels: bug
