Repository pontem-network/dove, pull requests merged in 2022-02, with the labels that each got.

#204 [v1.6] update dove tests
  Cargo.lock
  README.md
  dove/src/call/cmd.rs
  dove/src/cmd/call.rs
  dove/src/cmd/run.rs
  dove/src/context.rs
  dove/src/lib.rs
  dove/tests/helper.rs
  dove/tests/test_cmd_dove_build.rs
  dove/tests/test_cmd_dove_call.rs
  dove/tests/test_cmd_dove_init.rs
  dove/tests/test_cmd_dove_new.rs
Labels: documentation

#206 [v1.6] SS58_ADDRESS hints
  README.md
  dove/src/cmd/call.rs
  dove/src/cmd/run.rs
Labels: documentation

#205 [v.1.6] $ dove key
  .github/workflows/ci.yaml
  Cargo.lock
  README.md
  dove/Cargo.toml
  dove/src/cli.rs
  dove/src/cmd/clean.rs
  dove/src/cmd/key.rs
  dove/src/cmd/mod.rs
  dove/src/lib.rs
  dove/src/wallet_key.rs
Labels: documentation, ci

#212 [v1.6] $ dove deploy [FILE_NAME|PATH] [OPTIONS]
  Cargo.lock
  Cargo.toml
  README.md
  dove/Cargo.toml
  dove/src/cmd/deploy.rs
  dove/src/cmd/key.rs
  dove/src/lib.rs
  dove/src/publish.rs
  dove/src/wallet_key.rs
  dove/tests/test_cmd_dove_deploy.rs
  pontem/client/Cargo.toml
  pontem/client/build.rs
  pontem/client/src/lib.rs
  pontem/hash_project/Cargo.toml
  pontem/hash_project/src/lib.rs
  pontem/pontemapi/Cargo.lock
  pontem/pontemapi/Cargo.toml
  pontem/pontemapi/metadata/pontem.scale
  pontem/pontemapi/src/lib.rs
Labels: documentation

#209 [v1.6] dove call: create and publish transactions
  README.md
  dove/src/call/cmd.rs
  dove/src/cmd/call.rs
  dove/src/cmd/run.rs
  dove/tests/test_cmd_dove_call.rs
Labels: documentation

#219 CI: add `dove prove` check, optimize job sequence
  .github/workflows/ci.yaml
Labels: ci

#211 [v1.6] $ dove view
  Cargo.lock
  Cargo.toml
  README.md
  dove/Cargo.toml
  dove/src/cli.rs
  dove/src/cmd/mod.rs
  dove/src/cmd/view.rs
  lang/Cargo.toml
  lang/src/compiler/address/ss58.rs
  lang/src/lib.rs
  lang/src/ss58.rs
  net/Cargo.toml
  net/src/dnode/client.rs
  net/src/dnode/mod.rs
  net/src/lib.rs
  net/src/pont/mod.rs
  resource-viewer/Cargo.toml
  resource-viewer/README.md
  resource-viewer/src/lib.rs
  resource-viewer/src/main.rs
  resource-viewer/src/ser.rs
  resource-viewer/src/tte.rs
Labels: documentation, resource viewer, compiler
